### ISSUE TITLE
@Types incorrect

### ISSUE THREAD

**Issue by Ketec** [JamieMason/karma-jasmine-matchers#13]
`npm install @types/jasmine-matchers --save-dev`
installs @types belonging to:  https://github.com/uxebu/jasmine-matchers

`npm install @types/jasmine-expect --save-dev`
installs correct types.

**Comment by ronniegane** [comment]
The README seems incorrect, it suggests to install `@types/jasmine-matchers`which is for version 0.2.30

[Link to the DefinitelyTyped source for `jasmine-matchers`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine-matchers/index.d.ts)

When it should be `@types/jasmine-expect` for version 3.7.0

[Link to the DefinitelyTyped source for `jasmine-expect`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine-expect/index.d.ts)

**Comment by JamieMason** [comment]
Thanks @Ketec, @ronniegane. I don't use TypeScript (yet) myself but maybe @davguij can address this? The section in the README was added in PR #12.

**Comment by Ketec** [comment]
Updated my post. somehow git editor was hiding everything with @

**Comment by davguij** [comment]
Yes, I found the `jasmine-matchers` @types, but now it seems they have been moved to `jasmine-expect`, so the @types file needs to be changed accordingly.
It would be much easier if `jasmine-expect` declared its @types in the `package.json` file, though.
On a side note, I used to work in an Angular CLI based project several months ago and these @types worked alright, but I just made a dummy project using the latest versions of it all and, even though the IDE can find the @types and so it doesn't complain, the Angular CLI refuses to run the tests:
`ERROR in ./src/app/app.component.spec.ts (37,15): Property 'toBeEvenNumber' does not exist on type 'Matchers<number>'.`
So I'm scratching my head now...

**Comment by davguij** [comment]
Oh, silly me... The `jasmine-expect` types need to be added to the `tsconfig.spec.json` file...
I'll open a new pull request ASAP.
