### ISSUE TITLE
Add support for Jest.toMatchSnapshot

### ISSUE THREAD

**Issue by dosborne** [JamieMason/karma-jasmine-matchers#15]
It would be great to have support for Jest.toMatchSnapshot matcher.  This would allow test cases written in Jest to work as expected with Jest and also run the same test in a browser using Karma.

**Comment by JamieMason** [comment]
I'm sorry @dosborne but I don't think this project is the right place to provide that feature, it is for registering a library to karma. best of luck in your search. thank you for contributing.
