### ISSUE TITLE
jasmine-expect 5.x ?

### ISSUE THREAD

**Issue by AbdealiJK** [JamieMason/karma-jasmine-matchers#21]
## Description
https://github.com/JamieMason/Jasmine-Matchers/issues/124 this issue is affecting me, and so i wanted to use the latest version of jasmine-expect.
But looks like this library hardcodes the version

**Comment by JamieMason** [comment]
Just published 5.0.0 quickly now @AbdealiJK

**Comment by AbdealiLoKo** [comment]
Thanks for the quick reply  - will try it out
