### ISSUE TITLE
TypeError: expect(...).toHaveMethod is not a function

### ISSUE THREAD

**Issue by MadaraUchiha** [JamieMason/karma-jasmine-matchers#7]
I've been trying to add jasmine-matchers to my Karma tests for a while now, and apparently it refuses to load.

I have the following config (with the irrelevant items left out):

```javascript
        frameworks: [
            'requirejs',
            'jasmine',
            'jasmine-matchers'
        ],

        // list of files / patterns to load in the browser
        files: [
            // ...
            'src/test/javascript/test-main.js'
        ],

        browsers: [
            'PhantomJS'
        ],

        plugins: [
            'karma-jasmine',
            'karma-jasmine-matchers',
            'karma-requirejs',
            'karma-junit-reporter',
            'karma-chrome-launcher',
            'karma-firefox-launcher',
            'karma-phantomjs-launcher'
        ]
```

The only thing I can think of that may collide is requirejs. The log shows that jasmine-matchers.js was indeed requested and loaded, also, looking at the browser running the karma tests, I can see jasmine-matchers.js in the resources tab.

Is it possible the karma-jasmine-matchers doesn't play nice with requirejs?

**Comment by JamieMason** [comment]
Which version of karma jasmine matchers are you on? I think that matcher landed in the most recent release.

**Comment by MadaraUchiha** [comment]
Yes, it would appear that it was on the 2.0.0-beta1 branch, which npm did not install by default. It may be worth to mark those in README.MD so that it's clear what's currently available and what is not.

**Comment by Dianna** [comment]
A README update would be helpful for this, I ran into the same issue.

**Comment by JamieMason** [comment]
Sorry about this @MadaraUchiha @Dianna, please find the README updated.
